/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiEnhancePromptRouteImport } from './routes/api/enhance-prompt'
import { Route as ApiVideoUploadImageRouteImport } from './routes/api/video/upload-image'
import { Route as ApiVideoGenerateFromImageRouteImport } from './routes/api/video/generate-from-image'
import { Route as ApiVideoGenerateRouteImport } from './routes/api/video/generate'
import { Route as ApiVideoFileRouteImport } from './routes/api/video/file'
import { Route as ApiStatusPromptIdRouteImport } from './routes/api/status.$promptId'
import { Route as ApiVideoStatusPromptIdRouteImport } from './routes/api/video/status.$promptId'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhancePromptRoute = ApiEnhancePromptRouteImport.update({
  id: '/api/enhance-prompt',
  path: '/api/enhance-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoUploadImageRoute = ApiVideoUploadImageRouteImport.update({
  id: '/api/video/upload-image',
  path: '/api/video/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenerateFromImageRoute =
  ApiVideoGenerateFromImageRouteImport.update({
    id: '/api/video/generate-from-image',
    path: '/api/video/generate-from-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVideoGenerateRoute = ApiVideoGenerateRouteImport.update({
  id: '/api/video/generate',
  path: '/api/video/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoFileRoute = ApiVideoFileRouteImport.update({
  id: '/api/video/file',
  path: '/api/video/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusPromptIdRoute = ApiStatusPromptIdRouteImport.update({
  id: '/api/status/$promptId',
  path: '/api/status/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStatusPromptIdRoute = ApiVideoStatusPromptIdRouteImport.update({
  id: '/api/video/status/$promptId',
  path: '/api/video/status/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/video': typeof VideoRoute
  '/api/enhance-prompt': typeof ApiEnhancePromptRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
  '/api/video/file': typeof ApiVideoFileRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/api/video/generate-from-image': typeof ApiVideoGenerateFromImageRoute
  '/api/video/upload-image': typeof ApiVideoUploadImageRoute
  '/api/video/status/$promptId': typeof ApiVideoStatusPromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/video': typeof VideoRoute
  '/api/enhance-prompt': typeof ApiEnhancePromptRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
  '/api/video/file': typeof ApiVideoFileRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/api/video/generate-from-image': typeof ApiVideoGenerateFromImageRoute
  '/api/video/upload-image': typeof ApiVideoUploadImageRoute
  '/api/video/status/$promptId': typeof ApiVideoStatusPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/video': typeof VideoRoute
  '/api/enhance-prompt': typeof ApiEnhancePromptRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
  '/api/video/file': typeof ApiVideoFileRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/api/video/generate-from-image': typeof ApiVideoGenerateFromImageRoute
  '/api/video/upload-image': typeof ApiVideoUploadImageRoute
  '/api/video/status/$promptId': typeof ApiVideoStatusPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/video'
    | '/api/enhance-prompt'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
    | '/api/video/file'
    | '/api/video/generate'
    | '/api/video/generate-from-image'
    | '/api/video/upload-image'
    | '/api/video/status/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/video'
    | '/api/enhance-prompt'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
    | '/api/video/file'
    | '/api/video/generate'
    | '/api/video/generate-from-image'
    | '/api/video/upload-image'
    | '/api/video/status/$promptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/video'
    | '/api/enhance-prompt'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
    | '/api/video/file'
    | '/api/video/generate'
    | '/api/video/generate-from-image'
    | '/api/video/upload-image'
    | '/api/video/status/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  VideoRoute: typeof VideoRoute
  ApiEnhancePromptRoute: typeof ApiEnhancePromptRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiStatusPromptIdRoute: typeof ApiStatusPromptIdRoute
  ApiVideoFileRoute: typeof ApiVideoFileRoute
  ApiVideoGenerateRoute: typeof ApiVideoGenerateRoute
  ApiVideoGenerateFromImageRoute: typeof ApiVideoGenerateFromImageRoute
  ApiVideoUploadImageRoute: typeof ApiVideoUploadImageRoute
  ApiVideoStatusPromptIdRoute: typeof ApiVideoStatusPromptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-prompt': {
      id: '/api/enhance-prompt'
      path: '/api/enhance-prompt'
      fullPath: '/api/enhance-prompt'
      preLoaderRoute: typeof ApiEnhancePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/upload-image': {
      id: '/api/video/upload-image'
      path: '/api/video/upload-image'
      fullPath: '/api/video/upload-image'
      preLoaderRoute: typeof ApiVideoUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/generate-from-image': {
      id: '/api/video/generate-from-image'
      path: '/api/video/generate-from-image'
      fullPath: '/api/video/generate-from-image'
      preLoaderRoute: typeof ApiVideoGenerateFromImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/generate': {
      id: '/api/video/generate'
      path: '/api/video/generate'
      fullPath: '/api/video/generate'
      preLoaderRoute: typeof ApiVideoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/file': {
      id: '/api/video/file'
      path: '/api/video/file'
      fullPath: '/api/video/file'
      preLoaderRoute: typeof ApiVideoFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/$promptId': {
      id: '/api/status/$promptId'
      path: '/api/status/$promptId'
      fullPath: '/api/status/$promptId'
      preLoaderRoute: typeof ApiStatusPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/status/$promptId': {
      id: '/api/video/status/$promptId'
      path: '/api/video/status/$promptId'
      fullPath: '/api/video/status/$promptId'
      preLoaderRoute: typeof ApiVideoStatusPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  VideoRoute: VideoRoute,
  ApiEnhancePromptRoute: ApiEnhancePromptRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiImageRoute: ApiImageRoute,
  ApiStatusPromptIdRoute: ApiStatusPromptIdRoute,
  ApiVideoFileRoute: ApiVideoFileRoute,
  ApiVideoGenerateRoute: ApiVideoGenerateRoute,
  ApiVideoGenerateFromImageRoute: ApiVideoGenerateFromImageRoute,
  ApiVideoUploadImageRoute: ApiVideoUploadImageRoute,
  ApiVideoStatusPromptIdRoute: ApiVideoStatusPromptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
