/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiStatusPromptIdRouteImport } from './routes/api/status.$promptId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusPromptIdRoute = ApiStatusPromptIdRouteImport.update({
  id: '/api/status/$promptId',
  path: '/api/status/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/image': typeof ApiImageRoute
  '/api/status/$promptId': typeof ApiStatusPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/generate'
    | '/api/history'
    | '/api/image'
    | '/api/status/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiStatusPromptIdRoute: typeof ApiStatusPromptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/$promptId': {
      id: '/api/status/$promptId'
      path: '/api/status/$promptId'
      fullPath: '/api/status/$promptId'
      preLoaderRoute: typeof ApiStatusPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiImageRoute: ApiImageRoute,
  ApiStatusPromptIdRoute: ApiStatusPromptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
